[theme]
# Visual focado em tecnologia e Engenharia de Dados
primaryColor = "#00ff88"           
backgroundColor = "#0e1117"        
secondaryBackgroundColor = "#1a1c24" 
textColor = "#fafafa"              
font = "sans serif"

[client]
# Remove o botão azul de "Deploy" e as opções de compartilhamento do GitHub para o usuário final
toolbarMode = "minimal"
showSidebarNavigation = true

[server]
# Otimiza para execução em servidor
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Desativa a coleta de telemetria para carregar mais rápido e garantir privacidade
gatherUsageStats = false
